### ISSUE TITLE
Touch & go replays

### ISSUE THREAD

**Issue by alphaTECH-Aus** [OpenDriver2/REDRIVER2#137]
**Describe the bug**
Mission-based replays have an objectively high chance of going out of sync for no apparent reason.

**To Reproduce**
Play mission To The Docks and attempt to watch the replay of your trip. It will de-sync within the first ten seconds. I am also having very little luck with Escape The Brazilians.

**Expected behavior**
Replays should not go out of sync.

**Screenshots**
N/A. I have [attached replay files from great runs](https://github.com/OpenDriver2/REDRIVER2/files/6719582/Desynced.replays.zip) that were rendered useless by de-synced replays.

**Environment and game (please complete the following information):**
 - Game version: 7.2, beta 3
 - Operating System: Windows 10, build 1909
 - CPU model: AMD Ryzen 7 3700X
 - GPU model: Nvidia GeForce RTX 2070 Super

**Additional context**
This will eventually cause me to break my PS4 controller.

**Comment by SoapyMan** [comment]
Replays themselves have very little chance of deviation because computer maths arent always perfect and can't match. The way replays working in Driver 2 is that player controls are ONLY recorded and game has to be run EXACTLY the same every time. This problem will remain forever until entire game replay system is heavily upgraded and it will not happen with REDRIVER2.

But there is a deal with Boats that makes deviation even more aggressive - i'll try to fix it but there is no warranty that it will work best.

**Comment by SoapyMan** [comment]
Replays with boats are now consistent (fixed in f7ec7b9)
