### ISSUE TITLE
Hijack The Truck escort will no longer pursue player

### ISSUE THREAD

**Issue by alphaTECH-Aus** [OpenDriver2/REDRIVER2#140]
**Describe the bug**
This mission and the escort was working fine some days ago. I've been playing it again today, and the escort will not pursue. It is behaving like a cop in a tunnel in OG Driver 2. The issue persists even after restarting REDRIVER 2.

**To Reproduce**
I don't know how I've caused this mission to be permabugged.

**Expected behavior**
The escort should aggressively pursue the player car.

**Video**
https://youtu.be/HjmP275CGRw

**Environment and game (please complete the following information):**
 - Game version: 7.2, beta 3
 - Operating System: Windows 10, build 1909
 - CPU model: AMD Ryzen 7 3700X
 - GPU model: Nvidia GeForce RTX 2070 Super

**Additional context**
My next troubleshooting step is to delete the config files, but first I'm offering up a bug hunt. [Recent log file attached](https://github.com/OpenDriver2/REDRIVER2/files/6737729/REDRIVER2.log), however I do not know if it will be any help since the game does not error or crash.

**Comment by SoapyMan** [comment]
From what I know this is a purely random bug. Do you use CD image method installation?

**Comment by alphaTECH-Aus** [comment]
Yes, my image is PAL v1.1; I have installed both discs and run the game from an image of disc 1. In this instance though, it is a permanent bug. Nothing that I have tried is changing the behaviour.

- Playing a mission in a different city
- Playing a mission with pursuers in a different city
- Deleting config.ini
- Restarting the application
- Restarting my PC

**Comment by SoapyMan** [comment]
Can you try old installation method with extracting one of game CD images to see if it's changes?

**Comment by alphaTECH-Aus** [comment]
I would rather not, I think that's barking up the wrong tree. This mission was working fine a few days ago and no files have been modified since then (just checked all the dates/times). 

What I did just find is that I can no longer change the cop difficulty. Where are the REDRIVER 2 settings stored?

**Comment by SoapyMan** [comment]
This is probably related to #132 - game for sure have different behaviour.

> I would rather not, I think that's barking up the wrong tree. 
This doesn't make sense to me. Why you reported the bug at first place and now doesn't want to assist check if it's pure random? I don't have an ability to check random bugs since I cannot reproduce them - I need exact PC and OS setup.

Additionally you can check artifact build if its running correctly.
https://ci.appveyor.com/project/SoapyMan/redriver2-10jm8/builds/39791938/job/5k97fxj5uh13v8jq/artifacts

**Comment by alphaTECH-Aus** [comment]
> This doesn't make sense to me. Why you reported the bug at first place and now doesn't want to assist check if it's pure random?

My issue is the expenditure of time when I know and can prove that no program files have been changed thus it cannot be a problem with the installation.

Regardless, I've found the issue. config.dat had become corrupt. [I've attached the bad file.](https://github.com/OpenDriver2/REDRIVER2/files/6737998/xconfig.zip) I have tested Hijack The Truck with a fresh config.dat and the pursuer is doing its thing again.

**Comment by SoapyMan** [comment]
It still doesn't mean that it isn't related to me as a programmer since i've seen lots of memory access corruptions related to issue #132. Also #139 fixes some critical write bugs in pathfinding (buffer overruns on writes) so it can be pretty related too and it could have overwritten the difficulty level setup (gCopDifficultyLevel should be at 0..2)
