### ISSUE TITLE
Compiled REDRIVER2 file does not run under Linux

### ISSUE THREAD

**Issue by igorhoop** [OpenDriver2/REDRIVER2#197]
I use Linux Mint. I downloaded the archive **REDRIVER2_Linux_Release.tar.gz**. 

Next, I executed a bash script to convert resources, everything was OK here. But when REDRIVER 2 starts, it writes me an error:

`bash: ./REDRIVER2: No such file or directory`

The file definitely exists, but **Linux Mint** does not want to execute it. The same problem with **Ubuntu**.

**Comment by SoapyMan** [comment]
It requires 32 bit libraries installed in the system. Check it with ldd.

**Comment by igorhoop** [comment]
I tried it:

```
hoop@hoop-PC:~/REDRIVER2$ ldd REDRIVER2 
	not a dynamic executable
```

**Comment by JohnEdwa** [comment]
Encountered this on my Steam Deck with with the flatpak installation as well, that one fails in [start.sh at line 41](https://github.com/OpenDriver2/REDRIVER2/blob/master/.flatpak/start.sh#L41) with the same error.

**Comment by igorhoop** [comment]
It seems that the problem with 32-bit libraries was solved by this installation:

`sudo apt-get install ia32-libs `

But it still fails to launch. The script was **_convert_cd_fmv_xa.sh** executed and copied all the necessary files to the DRIVER2 directory. The catalog began to weigh 1.5 GB. However, an error occurs during startup REDRIVER:

```
Cannot initialize REDRIVER2
Game files not found by folder 'DRIVER2\'
```
I began to think that the binary is looking for a path in the `DRIVER\` directory - it tries to use **reverse slash, as in Windows**, and therefore does not find my directory DRIVER2

**Comment by enipklacus** [comment]
I'm experiencing the same issue (`Game files not found by folder 'DRIVER2\'`). Building from source or using the flatpak package have no difference.
BTW: running Arch.

**Comment by igorhoop** [comment]
The problem has been resolved. I used a launcher for **Windows** (Launcher.exe) to export files from the PS1 image.

Then I moved this directory with files to **Linux**, and everything works.

Conclusion: the script `_convert_cd_fmv_xa.sh` is not working correctly

**Comment by flutterbrony** [comment]
Why is it marked as completed since there is really an issue with the linux installer ?

**Comment by igorhoop** [comment]
> Why is it marked as completed since there is really an issue with the linux installer ?

The developer has not responded for too long, but for me the problem has already been resolved.

So I decided to close this issue.

**Comment by stephensrmmartin** [comment]
Note for others: The reason this is failing, is because the flatpak that is installed doesn't contain the lib32 libraries.

I discovered this because I can do the following:

1. flatpak --user run --command=sh io.github.opendriver2.Redriver2
2. Navigate to /app/game/bin
3. Run ./REDRIVER2; it will fail with `sh: ./REDRIVER2: No such file or directory`, even though clearly it exists.
4. file ./REDRIVER2: `./REDRIVER2: ELF 32-bit LSB pie executable, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.2, BuildID[sha1]=f8109635d978bfb4a98baa4d422e1bf417f6118d, for GNU/Linux 3.2.0, stripped`
5. ldd ./REDRIVER2: `        not a dynamic executable`
6. This error only occurs when a loader is not present on the system.
7. Exit the shell, back to the host system, then navigate to ~/.local/share/flatpak/app/io.github.opendriver2.Redriver2/current/active/files/game/bin
8. ldd ./REDRIVER2: ```        linux-gate.so.1 (0xf7fa7000)
        libjpeg.so.8 => /usr/lib32/libjpeg.so.8 (0xf70db000)
        libopenal.so.1 => /usr/lib32/libopenal.so.1 (0xf6e75000)
        libSDL2-2.0.so.0 => /usr/lib32/libSDL2-2.0.so.0 (0xf6e0c000)
        libdl.so.2 => /usr/lib32/libdl.so.2 (0xf6e07000)
        libstdc++.so.6 => /usr/lib32/libstdc++.so.6 (0xf6b82000)
        libm.so.6 => /usr/lib32/libm.so.6 (0xf6a97000)
        libgcc_s.so.1 => /usr/lib32/libgcc_s.so.1 (0xf6a63000)
        libc.so.6 => /usr/lib32/libc.so.6 (0xf6830000)
        /lib/ld-linux.so.2 => /usr/lib/ld-linux.so.2 (0xf7faa000)```

I think the only way to fix this would be to modify the flatpak runtime to include the ia32/lib32 libraries. It *should* be running, but the flatpak environment itself lacks the 32bit libraries. When you run it straight from the host, the app launches, but fails because it can't find the game files. I imagine one could modify the config.ini to point to the host location, and it all may work.

Alternatively, the flatpak could be avoided altogether; I imagine compiling from scratch may actually work better on arch, rather than trying to maintain a modified flatpak environment.

**Comment by stephensrmmartin** [comment]
Update: I modified the config to have:
```
[fs]
# dataFolder=REDRIVER2
dataFolder=/home/my_user_name/.var/app/io.github.opendriver2.Redriver2/data/
```
And it still failed due to seg fault:
```
*** buffer overflow detected ***: terminated
zsh: IOT instruction (core dumped)  ./REDRIVER2
```

So I think this would need to be recompiled on arch, or the Flatpak runtime would need to include the 32bit libs.

**Comment by B-Nerd** [comment]
on arch linux you need lib32-libjpeg-turbo & lib32-sdl2-compat
