### ISSUE TITLE
Support of original translations

### ISSUE THREAD

**Issue by SoapyMan** [OpenDriver2/REDRIVER2#28]
Required work
- [x] Convert all English strings to support language text file lookup
- [x] Add configuration setting for language

Add original language text files:
- [x] English - SLES-02993 / SLUS-01161
- [x] Italian - SLES-02996
- [x] German - SLES-12995
- [x] French - SLES-02994
- [x] Spanish - SLES-02997

**Comment by 50thomatoes50** [comment]
i didn't knew how they would do translation for the game so i had a look.
looks like a lot of stuff is hardcoded in the PS-exe.
things like damage and replay stuff are only available there.
that means we will need to hardcode it too and just use preprocessor switch to choose the language.

I found some translation in `FRONTEND.BIN` but look like the format change between 1.0 and 1.1 PAL
Mine is Fr SLES-02994, It start with `Player 2`, `Player 1` (yes in that order because), then some district names, then mission name or mission strings
what i found weird is that those are also in the PS-exe and it's not used at all in src_rebuild

**Comment by Jordem** [comment]
Hi,
I just recently found this project and it's pretty impressive.
Since I own the SLES-02995/12995 v1.0 (GERMAN) version, I started to translate the texts based on the Strings I found in the locations described above.
I could directly translate most of them, but some of them I couldn't find in the original files so I used an "as close as" possible translation.
Where could I commit those two files for review - if interested?

**Comment by SoapyMan** [comment]
Hey! @Jordem 
Yes - you can make a pull request with the added translation files. I'll check and accept it.

**Comment by Jordem** [comment]
Sadly, I have no clue about GitHub at all or pull requests.
I uploaded the two files packed in a ZIP file here:

[https://ufile.io/azjg6o8k](https://ufile.io/azjg6o8k)

**Comment by SoapyMan** [comment]
Added with 6.0a alpha
