### ISSUE TITLE
Gamepad controls improvements (analog input)

### ISSUE THREAD

**Issue by DCxDemo** [OpenDriver2/REDRIVER2#43]
What do you think about implementing an alternative analog input scheme for the gamepad (make both classic and alternative available via a switch)? The original seems to be using digital input even if dualshock is used.
RT (R2) = analog accelerate
LT (L2) = analog reverse
Left stick = analog steer
Right stick = control camera, either original R2, L2, R2+L2 mapped to left, right, down, or gta-sa style free camera

Also it seems the original game doesn't allow both dpad and left stick to be used simultaneously.
Emulated version chooses input type depending on the gamepad type (digital/dualshock)
Port uses a weird scheme where dpad works until any stick is touched, then dpad can't steer anymore. That's confusing at the very least.

My gamepad input is going through x360ce, everything mapped correctly, in case if it's important.

**Comment by slowriderxcorps** [comment]
In addition to this, I would personally hope to see if it's possible to reintroduce something that was in the original Driver but inexplicably missing from the sequel: an option to toggle the Automatic Handbrake off. For me, it always triggers at all the wrong times and it makes driving with any semblance of full control a throw of the dice, since at any moment you could just instantly be facing backwards when you were only trying to avoid oncoming traffic.

**Comment by alidayday** [comment]
hi mate,  could you help?, in redriver2 whenever i connect my ps2 controller, the  camera goes revers, like pressing L2 AND R2, any solution?

**Comment by SoapyMan** [comment]
@DCxDemo controller bindings now can be reassigned.
