### ISSUE TITLE
In the Havana mission "Follow Up the Lead" car gets stuck in a wall if chooses the alley path.

### ISSUE THREAD

**Issue by daniel-c910** [OpenDriver2/REDRIVER2#58]
When I was playing the mission, I noticed this bug when the car decided to use the alley near the end of this mission, after passing by the alley it just when straight into the wall, remaining stuck there for the rest of the mission.

This happens when the AI decides to use the alleyway path because in the other paths the car manages to reach the end of the mission just fine. For the note, I also noticed that sometimes the car before turning decides anyway to change line then turn, as if there was traffic in the junction.

![REDRIVER2 08_12_2020 16_51_35](https://user-images.githubusercontent.com/75336421/101507511-ea9cc980-3976-11eb-8564-563c62aaba25.png)
![REDRIVER2 08_12_2020 16_51_54](https://user-images.githubusercontent.com/75336421/101507512-ebcdf680-3976-11eb-9870-143548b85358.png)

**Comment by SoapyMan** [comment]
@daniel-c910 do you play with only using a Appveyor release or you use github release? Because we had most of chases re-recorded with Driver Madness people.

Also, this is a side effect of reverse engineering which I cannot fix. Car collision code is slightly different than in OG game. And if it collides the wall somewhere it *might* deviate. In some other missions with more severe collision cases it actually *might* not deviate.

**Comment by daniel-c910** [comment]
I'm using the github release.

Alright then, I didn't know that, thanks for the information.
