### ISSUE TITLE
quick save / load, free save

### ISSUE THREAD

**Issue by AD010** [OpenDriver2/REDRIVER2#85]
please add quick save/load anytime (hotkey), for example in emulators, the game is difficult for casual gamers

**Comment by SoapyMan** [comment]
Speaking of the save states like in the emulator - cannot be done. Game is not running in the shared/virtual memory. I can only record chases with decreased difficulty.

**Comment by AD010** [comment]
but old games on PC (FPS, Stealth, Strategy) have free save / load

**Comment by AD010** [comment]
> 
> 
> Speaking of the save states like in the emulator - cannot be done. Game is not running in the virtual memory. I can only record chases with decreased difficulty.

but old games on PC (FPS, Stealth, Strategy) have free save / load

**Comment by SoapyMan** [comment]
They may have that because they have an entire system that save/restore system of objects and the game itself is very adapted for that (I developed similar systems prior to The Driver Syndicate). But it is complex - especially when you have to deal with the integrity and have to take car slots, mission states, random state, replays and other things into account. And it is unlike the emulator which is have to deal with only a "paused" CPU state, RAM state and GPU state which you can easily load up and continue.

**Comment by SoapyMan** [comment]
Also, I haven't seen racing games using such mid-pursuit save states due to the breaking game design rule of challenge. For me it makes game even more uninteresting and dull with such comforts.
