### ISSUE TITLE
Analogue control disables digital pad

### ISSUE THREAD

**Issue by Kroc** [OpenDriver2/REDRIVER2#90]
Artefact build, April 17th.

When in-game, the D-pad will move as expected. If I then move the analogue stick, the analogue stick begins working and the digital pad no longer responds! I am using an 8-BitDo SF30 Pro gamepad, running in XBox mode (XInput). I would like the digital pad to remain functional, as I switch between analogue and digital often for comfort.

**Comment by SoapyMan** [comment]
The reason why Analog mode is enabled when you use sticks is to "emulate" analog mode button (due to I cannot use controller Home button). To disable analog mode you have to press any control button on keyboard (arrows for example)

It is also described here https://github.com/OpenDriver2/REDRIVER2/wiki/Controls

**Comment by Kroc** [comment]
Sure, that's what happens as far as a PSX is concerned, but that shouldn't be the case for a PC game; no other PC game does this, and digital / analogue controls should always be available.
