### ISSUE TITLE
[Gameplay Improvement] Increase draw distance for objects if possible.

### ISSUE THREAD

**Issue by Sqrdelta** [OpenDriver2/REDRIVER2#95]
Objects like buildings, environment stuff ecc so the screen won't feel much empty while driving around. If it's possible to do so.

**Comment by SoapyMan** [comment]
This is not gameplay improvement.

Also, since it's a direct source port of Playstation version with it's limits, it's not possible to extend draw distance further (5-6 regions ahead) due to how game is built. OpenDriverEngine will be capable of unlimited drawing distance.

P.S. why is everyone is so obsessed with drawing distance?
